secure_ingress:
  name: dashboard-ingress
  backendIsHttps: true
  ipWhitelist: 47.196.14.245/32
  hosts:
    - name: infra-craigmiller160.ddns.net
      services:
        - path: /dashboard/(.*)
          serviceName: kubernetes-dashboard
          portNumber: 443